version: "3"
services:
  mysql57:
    image: mysql:5.7.26
    restart: unless-stopped
    container_name: mysql57
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "mysql57"
    volumes:
      - mysql57-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
volumes:
  mysql57-data:
